
import React, { useState } from 'react';
import { Document, ResearchFolder, Language } from '../types';
import { Plus, Folder, Trash2, Zap, FileText, ChevronDown, ChevronRight, Download, Loader2 } from 'lucide-react';
import JSZip from 'jszip';

interface FolderManagerProps {
  documents: Document[];
  folders: ResearchFolder[];
  language: Language;
  onAddFolder: (name: string) => void;
  onDeleteFolder: (id: string) => void;
  onClassify: () => void;
  isClassifying: boolean;
}

const FolderManager: React.FC<FolderManagerProps> = ({
  documents,
  folders,
  language,
  onAddFolder,
  onDeleteFolder,
  onClassify,
  isClassifying
}) => {
  const [newFolderName, setNewFolderName] = useState('');
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());
  const [downloadingFolderId, setDownloadingFolderId] = useState<string | null>(null);

  const toggleFolder = (id: string) => {
    const next = new Set(expandedFolders);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setExpandedFolders(next);
  };

  const handleAdd = () => {
    if (!newFolderName.trim()) return;
    onAddFolder(newFolderName);
    setNewFolderName('');
  };

  const handleDownloadFolder = async (folder: ResearchFolder, e: React.MouseEvent) => {
    e.stopPropagation();
    const folderDocs = documents.filter(d => d.folderIds?.includes(folder.id) && d.status === 'SUCCESS' && d.analysis);
    
    if (folderDocs.length === 0) {
        alert(language === 'vi' ? 'Thư mục trống hoặc các tài liệu chưa được phân tích xong.' : 'Folder is empty or documents are not analyzed yet.');
        return;
    }

    setDownloadingFolderId(folder.id);

    try {
        const zip = new JSZip();
        const rootFolder = zip.folder(folder.name.replace(/[^a-z0-9]/gi, '_'));

        folderDocs.forEach(doc => {
            const a = doc.analysis!;
            let content = `DOCUMENT ANALYSIS REPORT\n`;
            content += `Generated by Insight Scholar\n\n`;
            content += `TITLE: ${a.title}\n`;
            content += `AUTHORS: ${a.authors.join(', ')}\n`;
            content += `CITATION: ${a.citation_apa}\n`;
            content += "==================================================\n\n";
            content += `1. THESIS & BACKGROUND:\n${a.thesis_background}\n\n`;
            content += `2. THEORETICAL FRAMEWORK:\n${a.theoretical_framework}\n\n`;
            content += `3. CONCEPTUAL FRAMEWORK:\n${a.conceptual_framework}\n\n`;
            content += `4. METHODOLOGY:\n${a.methodology}\n\n`;
            content += `5. RESULTS & INTERPRETATION:\n${a.results_interpretation}\n\n`;
            content += `6. SCOPE & LIMITATIONS:\n${a.scope_limitations}\n\n`;
            content += `7. CONCLUSION:\n${a.overall_conclusion}\n\n`;

            // Sanitize filename
            const safeName = (a.title || doc.fileName).replace(/[^a-z0-9]/gi, '_').substring(0, 50);
            rootFolder?.file(`${safeName}.txt`, content);
        });

        const content = await zip.generateAsync({ type: "blob" });
        
        // Trigger download
        const url = URL.createObjectURL(content);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${folder.name}_Analysis.zip`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);

    } catch (error) {
        console.error("Error creating zip", error);
        alert("Failed to create zip file.");
    } finally {
        setDownloadingFolderId(null);
    }
  };

  const analyzedDocsCount = documents.filter(d => d.status === 'SUCCESS').length;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header & Controls */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
        <h2 className="text-xl font-bold text-slate-800 mb-2">
          {language === 'vi' ? 'Thư mục Thông minh' : 'Smart Folders'}
        </h2>
        <p className="text-slate-500 mb-6 text-sm">
          {language === 'vi' 
            ? 'Tạo các mục tiêu nghiên cứu (folder). AI sẽ tự động phân loại tài liệu vào một hoặc nhiều folder phù hợp.' 
            : 'Create research objectives (folders). AI will automatically classify documents into one or more matching folders.'}
        </p>

        <div className="flex gap-4 items-end">
          <div className="flex-1">
            <label className="block text-xs font-semibold text-slate-500 uppercase mb-1">
              {language === 'vi' ? 'Tên thư mục mới' : 'New Folder Name'}
            </label>
            <div className="flex gap-2">
              <input 
                type="text" 
                value={newFolderName}
                onChange={(e) => setNewFolderName(e.target.value)}
                placeholder={language === 'vi' ? "Ví dụ: Nghiên cứu Định lượng, AI trong Y tế..." : "E.g., Quantitative Studies, AI in Healthcare..."}
                className="flex-1 border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-accent"
                onKeyDown={(e) => e.key === 'Enter' && handleAdd()}
              />
              <button 
                onClick={handleAdd}
                className="bg-slate-100 text-slate-700 px-4 py-2 rounded-lg hover:bg-slate-200 border border-slate-200"
              >
                <Plus size={20} />
              </button>
            </div>
          </div>
          
          <button 
            onClick={onClassify}
            disabled={isClassifying || folders.length === 0 || analyzedDocsCount === 0}
            className="bg-accent text-white px-6 py-2 rounded-lg hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 h-[42px] font-medium"
          >
             <Zap size={18} fill={isClassifying ? "none" : "currentColor"} className={isClassifying ? "animate-spin" : ""} />
             {isClassifying 
               ? (language === 'vi' ? 'Đang phân loại...' : 'Classifying...') 
               : (language === 'vi' ? 'Tự động Phân loại' : 'Auto Classify')
             }
          </button>
        </div>
      </div>

      {/* Folders List */}
      <div className="space-y-4">
        {folders.length === 0 && (
          <div className="text-center p-12 border-2 border-dashed border-slate-200 rounded-xl text-slate-400">
             <Folder size={48} className="mx-auto mb-2 opacity-20" />
             <p>{language === 'vi' ? 'Chưa có thư mục nào. Hãy tạo một thư mục để bắt đầu.' : 'No folders yet. Create one to start.'}</p>
          </div>
        )}

        {folders.map(folder => {
          // Find docs in this folder
          const docsInFolder = documents.filter(d => d.folderIds?.includes(folder.id));
          const isExpanded = expandedFolders.has(folder.id);
          const isDownloading = downloadingFolderId === folder.id;

          return (
            <div key={folder.id} className="bg-white border border-slate-200 rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
              <div 
                className="flex items-center justify-between p-4 bg-slate-50 cursor-pointer select-none"
                onClick={() => toggleFolder(folder.id)}
              >
                <div className="flex items-center gap-3">
                   <button className="text-slate-400">
                      {isExpanded ? <ChevronDown size={20} /> : <ChevronRight size={20} />}
                   </button>
                   <Folder className="text-accent" size={20} fill="currentColor" fillOpacity={0.2} />
                   <h3 className="font-semibold text-slate-800">{folder.name}</h3>
                   <span className="bg-white px-2 py-0.5 rounded-full text-xs border border-slate-200 text-slate-500 font-mono">
                      {docsInFolder.length}
                   </span>
                </div>
                
                <div className="flex items-center gap-1">
                    <button
                        onClick={(e) => handleDownloadFolder(folder, e)}
                        disabled={isDownloading || docsInFolder.length === 0}
                        title={language === 'vi' ? "Tải xuống toàn bộ (ZIP)" : "Download All (ZIP)"}
                        className="text-slate-400 hover:text-green-600 p-2 hover:bg-green-50 rounded-full transition-colors disabled:opacity-30 disabled:hover:bg-transparent"
                    >
                        {isDownloading ? <Loader2 size={16} className="animate-spin text-green-600" /> : <Download size={16} />}
                    </button>
                    <button 
                        onClick={(e) => { e.stopPropagation(); onDeleteFolder(folder.id); }}
                        className="text-slate-400 hover:text-error p-2 hover:bg-red-50 rounded-full transition-colors"
                        title={language === 'vi' ? "Xóa thư mục" : "Delete Folder"}
                    >
                        <Trash2 size={16} />
                    </button>
                </div>
              </div>

              {isExpanded && (
                <div className="border-t border-slate-100 p-2 bg-white">
                  {docsInFolder.length === 0 ? (
                    <div className="p-4 text-sm text-slate-400 italic text-center">
                       {language === 'vi' ? 'Thư mục trống.' : 'Empty folder.'}
                    </div>
                  ) : (
                    <div className="grid gap-2">
                       {docsInFolder.map(doc => (
                         <div key={doc.id} className="flex items-center gap-3 p-3 hover:bg-slate-50 rounded-lg border border-transparent hover:border-slate-100 transition-colors">
                            <FileText size={16} className="text-slate-400" />
                            <div className="overflow-hidden">
                                <p className="text-sm font-medium text-slate-700 truncate">{doc.analysis?.title || doc.fileName}</p>
                                <p className="text-xs text-slate-400 truncate">{doc.analysis?.authors.join(', ') || 'Unknown Author'}</p>
                            </div>
                         </div>
                       ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default FolderManager;
